name: llc-test
channels:
  - conda-forge
dependencies:
  - python>=3.8*
  - setuptools>=19.6*
  - numba>=0.5
  - numpy>=1.18*
  - numpydoc>=0.5*
  - scipy>=1.6*
  - pytest>=6*
  - coverage>=4.0
  - pytest-cov>=2.2
  - hypothesis>=5*
